name: CI backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: 'npm'
      - name: Install dependencies 
        run: npm install --no-audit --no-fund --no-optional
      - name: Lint
        run: npm run lint      
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test


          
