name: CI frontend

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: frontend
      - uses: actions/setup-node@v3
        with:
            node-version: 18.4.0
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

          