name: CI frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: 18.4.0
      - name: Install dependencies 
        working-directory: frontend
        run: npm install
      - name: Lint
        working-directory: frontend
        run: npm run lint

          
